package com.xworkz.lifestyle;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import java.util.List;

public class CoreRunner {
    public static void main(String[] args) {
        System.out.println("The life style data");
        ApplicationContext applicationContext=new AnnotationConfigApplicationContext(Configure.class);
        System.out.println("1.The mall data");
        List<String> mall=applicationContext.getBean("Mall", List.class);
        System.out.println("mall"+mall);
        System.out.println("-----------------------------------------------");
        System.out.println("1.The beauty product details");
        List<String> beauty=applicationContext.getBean("beauty", List.class);
        System.out.println("BeautyProducts:"+beauty);
        System.out.println("-----------------------------------------------");
        System.out.println("3.The phone number data: ");
        List<String> phone=applicationContext.getBean("phone", List.class);
        System.out.println("Phone:"+phone);
        System.out.println("-----------------------------------------------");
        System.out.println("4. The countries data: ");
        List<String> countries = applicationContext.getBean("countries", List.class);
        System.out.println("Countries: " + countries);
        System.out.println("-----------------------------------------------");
        System.out.println("5. The cities data: ");
        List<String> cities = applicationContext.getBean("cities", List.class);
        System.out.println("Cities: " + cities);
        System.out.println("-----------------------------------------------");
        System.out.println("6. The vehicle brands data: ");
        List<String> vehicles = applicationContext.getBean("vehicles", List.class);
        System.out.println("Vehicles: " + vehicles);
        System.out.println("-----------------------------------------------");
        System.out.println("7. The laptop brands data: ");
        List<String> laptops = applicationContext.getBean("laptops", List.class);
        System.out.println("Laptops: " + laptops);
        System.out.println("-----------------------------------------------");
        System.out.println("8. The fruits data: ");
        List<String> fruits = applicationContext.getBean("fruits", List.class);
        System.out.println("Fruits: " + fruits);
        System.out.println("-----------------------------------------------");
        System.out.println("9. The vegetables data: ");
        List<String> vegetables = applicationContext.getBean("vegetables", List.class);
        System.out.println("Vegetables: " + vegetables);
        System.out.println("-----------------------------------------------");
        System.out.println("10. The pincode data: ");
        List<Integer> pincodes = applicationContext.getBean("pincode", List.class);
        System.out.println("Pincodes: " + pincodes);
        System.out.println("-----------------------------------------------");
        System.out.println("11. The prices data: ");
        List<Double> prices = applicationContext.getBean("prices", List.class);
        System.out.println("Prices: " + prices);
        System.out.println("-----------------------------------------------");
        System.out.println("12. The ratings data: ");
        List<Float> ratings = applicationContext.getBean("ratings", List.class);
        System.out.println("Ratings: " + ratings);
        System.out.println("-----------------------------------------------");
        System.out.println("13. The boolean values data: ");
        List<Boolean> boolValues = applicationContext.getBean("boolValues", List.class);
        System.out.println("Boolean Values: " + boolValues);
        System.out.println("-----------------------------------------------");
        System.out.println("14. The characters data: ");
        List<Character> characters = applicationContext.getBean("characters", List.class);
        System.out.println("Characters: " + characters);
        System.out.println("-----------------------------------------------");
        System.out.println("15. The employees data: ");
        List<String> employees = applicationContext.getBean("employees", List.class);
        System.out.println("Employees: " + employees);
        System.out.println("-----------------------------------------------");
        System.out.println("16. The banks data: ");
        List<String> banks = applicationContext.getBean("banks", List.class);
        System.out.println("Banks: " + banks);
        System.out.println("-----------------------------------------------");
        System.out.println("17. The colors data: ");
        List<String> colors = applicationContext.getBean("colors", List.class);
        System.out.println("Colors: " + colors);
        System.out.println("-----------------------------------------------");
        System.out.println("18. The mobile brands data: ");
        List<String> mobileBrands = applicationContext.getBean("mobileBrands", List.class);
        System.out.println("Mobile Brands: " + mobileBrands);
        System.out.println("-----------------------------------------------");
        System.out.println("19. The ice cream flavors data: ");
        List<String> icecreams = applicationContext.getBean("icecream", List.class);
        System.out.println("Ice Creams: " + icecreams);
        System.out.println("-----------------------------------------------");
        System.out.println("20. The clothing brands data: ");
        List<String> clothing = applicationContext.getBean("clothing", List.class);
        System.out.println("Clothing Brands: " + clothing);
        System.out.println("-----------------------------------------------");
        System.out.println("21. The bike brands data: ");
        List<String> bikes = applicationContext.getBean("bikes", List.class);
        System.out.println("Bike Brands: " + bikes);
        System.out.println("-----------------------------------------------");
        System.out.println("22. The books data: ");
        List<String> books = applicationContext.getBean("books", List.class);
        System.out.println("Books: " + books);
        System.out.println("-----------------------------------------------");
        System.out.println("23. The movies data: ");
        List<String> movies = applicationContext.getBean("movies", List.class);
        System.out.println("Movies: " + movies);
        System.out.println("-----------------------------------------------");
        System.out.println("24. The TV brands data: ");
        List<String> tvBrands = applicationContext.getBean("tvBrands", List.class);
        System.out.println("TV Brands: " + tvBrands);
        System.out.println("-----------------------------------------------");
        System.out.println("25. The dairy products data: ");
        List<String> dairy = applicationContext.getBean("dairy", List.class);
        System.out.println("Dairy Products: " + dairy);
        System.out.println("-----------------------------------------------");
        System.out.println("26. The stationery data: ");
        List<String> stationery = applicationContext.getBean("stationery", List.class);
        System.out.println("Stationery: " + stationery);
        System.out.println("-----------------------------------------------");
        System.out.println("27. The games data: ");
        List<String> games = applicationContext.getBean("games", List.class);
        System.out.println("Games: " + games);
        System.out.println("-----------------------------------------------");
        System.out.println("28. The programming languages data: ");
        List<String> languages = applicationContext.getBean("languages", List.class);
        System.out.println("Languages: " + languages);
        System.out.println("-----------------------------------------------");
        System.out.println("29. The salaries data: ");
        List<Double> salaries = applicationContext.getBean("salaries", List.class);
        System.out.println("Salaries: " + salaries);
        System.out.println("-----------------------------------------------");
        System.out.println("30. The roll numbers data: ");
        List<Integer> rollNumbers = applicationContext.getBean("rollNumbers", List.class);
        System.out.println("Roll Numbers: " + rollNumbers);
        System.out.println("-----------------------------------------------");
        System.out.println("31. The ages data: ");
        List<Integer> ages = applicationContext.getBean("ages", List.class);
        System.out.println("Ages: " + ages);
        System.out.println("-----------------------------------------------");
        System.out.println("32. The temperature data: ");
        List<Float> temperature = applicationContext.getBean("temperature", List.class);
        System.out.println("Temperature: " + temperature);
        System.out.println("-----------------------------------------------");
        System.out.println("33. The car models data: ");
        List<String> carModels = applicationContext.getBean("carModels", List.class);
        System.out.println("Car Models: " + carModels);
        System.out.println("-----------------------------------------------");
        System.out.println("34. The animals data: ");
        List<String> animals = applicationContext.getBean("animals", List.class);
        System.out.println("Animals: " + animals);
        System.out.println("-----------------------------------------------");
        System.out.println("35. The subjects data: ");
        List<String> subjects = applicationContext.getBean("subjects", List.class);
        System.out.println("Subjects: " + subjects);
        System.out.println("-----------------------------------------------");

    }


}
